name: Call Beta Bot

on:
  # Triggers the workflow on push to beta branch or changes in a pull request to main branch
  push:
    branches: [ "beta" ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, closed, labeled, unlabeled ]
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Calls the latest Beta Bot with the current context
  call-workflow:
    uses: genexuslabs/auto-prs-merger/.github/workflows/run-beta-bot.yml@master
    secrets: inherit
